### PR TITLE
sortMounts stable and remove alphabetical order

### PR DESCRIPTION
**Pull request by Epsilon314**
PR for  #240

### CODE REVIEW

**Review by elezar — COMMENTED** [review]
Thanks @Epsilon314

What is the expected behaviour when the mount being injected has:
1. the same number of parts
2. a greater number of parts

The behaviour for 1 seems undefined and was the motivation for the alphabetical sorting in the first place.

**Comment by Epsilon314** [comment]
@elezar For mounts with same number of parts, its original order will be kept (stable sort). Since containerd also uses stable sort, users can therefore arrange the order their mounts (of same number of parts ) in container spec if they do need a specific order.

**Comment by elezar** [comment]
Ok, so if we add mounts these would always be added after the existing mounts. Could you add tests for those cases?

**Comment by Epsilon314** [comment]
> Ok, so if we add mounts these would always be added after the existing mounts. Could you add tests for those cases?

@elezar OK

**Review by klihub — APPROVED** [review]

**Review by bart0sh — APPROVED** [review]

**Pull request merged**
